name: timetable
description: A timetable application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase Authentication (e-mail in this case)
  firebase_auth: ^3.8.0

  # Firebase database
  cloud_firestore: ^3.4.9

  # Firebase storage for files
  firebase_storage: ^10.3.8

  # State management
  flutter_bloc: ^8.1.1

  equatable: ^2.0.5

  # Either<L,R>
  dartz: ^0.10.1

  # local storage
  shared_preferences: ^2.0.15

  # check internet connection real-time
  internet_connection_checker: ^0.0.1+4

  #service locator
  get_it: ^7.2.0

  #text icons set
  fluttericon: ^2.0.0

  #select image from camera or gallery
  image_picker: ^0.8.5+3

  # easy way to get standard phone folders, such as temp dir, e.t.c.
  path_provider: ^2.0.11

  # for svg graphics on screens
  flutter_svg: ^1.1.5

  numberpicker: ^2.1.1

  # nice loading effects for widgets
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  fake_cloud_firestore: ^1.3.2
  firebase_storage_mocks: ^0.5.1
  firebase_auth_mocks: ^0.8.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Medium.ttf
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
